//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grow_Up.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grow_Up.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000004810A44B.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with #tag.
        /// </summary>
        public static string TextID1 {
            get {
                return ResourceManager.GetString("TextID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to technical support/feedback email.
        /// </summary>
        public static string TextID10 {
            get {
                return ResourceManager.GetString("TextID10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string TextID11 {
            get {
                return ResourceManager.GetString("TextID11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string TextID12 {
            get {
                return ResourceManager.GetString("TextID12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We respect your privacy. We may access your location just to provide you with more relevant places address. Your information will not be used for any other purposes..
        /// </summary>
        public static string TextID13 {
            get {
                return ResourceManager.GetString("TextID13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select other app as lockscreen provider.
        /// </summary>
        public static string TextID14 {
            get {
                return ResourceManager.GetString("TextID14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select month and background.
        /// </summary>
        public static string TextID15 {
            get {
                return ResourceManager.GetString("TextID15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you allow the application to use your GPS position?.
        /// </summary>
        public static string TextID16 {
            get {
                return ResourceManager.GetString("TextID16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network is not avaiable.
        /// </summary>
        public static string TextID17 {
            get {
                return ResourceManager.GetString("TextID17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location service is not avaiable..
        /// </summary>
        public static string TextID18 {
            get {
                return ResourceManager.GetString("TextID18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is saved to camera roll.
        /// </summary>
        public static string TextID19 {
            get {
                return ResourceManager.GetString("TextID19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TextID2 {
            get {
                return ResourceManager.GetString("TextID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Amazing Daily Photo for a while now, would you like to review this app?.
        /// </summary>
        public static string TextID20 {
            get {
                return ResourceManager.GetString("TextID20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review my app.
        /// </summary>
        public static string TextID21 {
            get {
                return ResourceManager.GetString("TextID21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These themes are not available for trial mode. Would you like to purchase?.
        /// </summary>
        public static string TextID22 {
            get {
                return ResourceManager.GetString("TextID22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextID23 {
            get {
                return ResourceManager.GetString("TextID23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TextID24 {
            get {
                return ResourceManager.GetString("TextID24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display in calendar.
        /// </summary>
        public static string TextID25 {
            get {
                return ResourceManager.GetString("TextID25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TextID26 {
            get {
                return ResourceManager.GetString("TextID26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add #tag.
        /// </summary>
        public static string TextID27 {
            get {
                return ResourceManager.GetString("TextID27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add location.
        /// </summary>
        public static string TextID28 {
            get {
                return ResourceManager.GetString("TextID28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to cloud.
        /// </summary>
        public static string TextID29 {
            get {
                return ResourceManager.GetString("TextID29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate calendar.
        /// </summary>
        public static string TextID3 {
            get {
                return ResourceManager.GetString("TextID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photos to upload.
        /// </summary>
        public static string TextID30 {
            get {
                return ResourceManager.GetString("TextID30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect Skydrive.
        /// </summary>
        public static string TextID31 {
            get {
                return ResourceManager.GetString("TextID31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Amazing Daily Photo folder in Skydrive.
        /// </summary>
        public static string TextID32 {
            get {
                return ResourceManager.GetString("TextID32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string TextID33 {
            get {
                return ResourceManager.GetString("TextID33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all.
        /// </summary>
        public static string TextID34 {
            get {
                return ResourceManager.GetString("TextID34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string TextID4 {
            get {
                return ResourceManager.GetString("TextID4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add caption.
        /// </summary>
        public static string TextID5 {
            get {
                return ResourceManager.GetString("TextID5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TextID6 {
            get {
                return ResourceManager.GetString("TextID6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string TextID7 {
            get {
                return ResourceManager.GetString("TextID7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string TextID8 {
            get {
                return ResourceManager.GetString("TextID8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Amazing Daily Photo, never miss any important event of your life!.
        /// </summary>
        public static string TextID9 {
            get {
                return ResourceManager.GetString("TextID9", resourceCulture);
            }
        }
    }
}
